package com.ims.oversea.framework.transaction.txmonitor.business.thing.entity.transactioninfo;

import javax.ejb.*;
import java.util.*;

public interface TransactionInfoEB extends javax.ejb.EJBLocalObject {
  public void setTransaction_id(String transaction_id);
  public String getTransaction_id();
  public void setHost_name(String host_name);
  public String getHost_name();
  public void setSystem_name(String system_name);
  public String getSystem_name();
  public void setMethod_name(String method_name);
  public String getMethod_name();
  public void setBank_code(String bank_code);
  public String getBank_code();
  public void setBranch_code(String branch_code);
  public String getBranch_code();
  public void setUser_id(String user_id);
  public String getUser_id();
  public void setChannel_type(String channel_type);
  public String getChannel_type();
  public void setBusiness_date(String business_date);
  public String getBusiness_date();
  public void setRegister_date(String register_date);
  public String getRegister_date();
  public void setEvent_no(String event_no);
  public String getEvent_no();
  public void setTransaction_no(String transaction_no);
  public String getTransaction_no();
  public void setOrg_seq(String org_seq);
  public String getOrg_seq();
  public void setIn_time(String in_time);
  public String getIn_time();
  public void setOut_time(String out_time);
  public String getOut_time();
  public void setResponse_time(String response_time);
  public String getResponse_time();
  public void setError_code(String error_code);
  public String getError_code();
  public void setIp_address(String ip_address);
  public String getIp_address();
  public void setTpfq(String tpfq);
  public String getTpfq();
  public void setStf_intime(String stf_intime);
  public String getStf_intime();
  public void setStf_outtime(String stf_outtime);
  public String getStf_outtime();
  public void setStf_interval(String stf_interval);
  public String getStf_interval();
  public void setBtf_intime(String btf_intime);
  public String getBtf_intime();
  public void setBtf_outtime(String btf_outtime);
  public String getBtf_outtime();
  public void setBtf_interval(String btf_interval);
  public String getBtf_interval();
  public void setEtf_intime(String etf_intime);
  public String getEtf_intime();
  public void setEtf_outtime(String etf_outtime);
  public String getEtf_outtime();
  public void setEtf_interval(String etf_interval);
  public String getEtf_interval();
}