package com.ims.oversea.cashCard.business.cashCard.entity;

import javax.ejb.*;
import java.util.*;
import java.math.*;

public interface CashCardEB extends javax.ejb.EJBLocalObject
{
    public String getBankType();
    public String getBankCode();
    public String getPrimaryAccountNo();
    public int getSequenceNo();
    public String getCardNumber();
    public void setBranchCode(String branchCode);
    public String getBranchCode();
    public void setType(String type);
    public String getType();
    public void setCifNo(String cifNo);
    public String getCifNo();
    public void setPasswordNo(String passwordNo);
    public String getPasswordNo();
    public void setInvalidAttemptCnt(int invalidAttemptCnt);
    public int getInvalidAttemptCnt();
    public void setSecondaryAccountNo(String secondaryAccountNo);
    public String getSecondaryAccountNo();
    public void setTernaryAccountNo(String ternaryAccountNo);
    public String getTernaryAccountNo();
    public void setDailyLimitCcy(String dailyLimitCcy);
    public String getDailyLimitCcy();
    public void setDailyLimitAmount(BigDecimal dailyLimitAmount);
    public BigDecimal getDailyLimitAmount();
    public void setDailyAccumAmount(BigDecimal dailyAccumAmount);
    public BigDecimal getDailyAccumAmount();
    public void setDailyTrfLimitCcy(String dailyTrfLimitCcy);
    public String getDailyTrfLimitCcy();
    public void setDailyTrfLimitAmount(BigDecimal dailyTrfLimitAmount);
    public BigDecimal getDailyTrfLimitAmount();
    public void setDailyTrfAccumAmount(BigDecimal dailyTrfAccumAmount);
    public BigDecimal getDailyTrfAccumAmount();
    public void setDailyAccumResetDate(String dailyAccumResetDate);
    public String getDailyAccumResetDate();
    public void setDailyAccumResetTime(String dailyAccumResetTime);
    public String getDailyAccumResetTime();
    public void setEffectiveDate(String effectiveDate);
    public String getEffectiveDate();
    public void setExpiryDate(String expiryDate);
    public String getExpiryDate();
    public void setStatus(String status);
    public String getStatus();
    public void setIncidentCode(String incidentCode);
    public String getIncidentCode();
    public void setFeeWaive(String feeWaive);
    public String getFeeWaive();
    public void setFeeCcy(String feeCcy);
    public String getFeeCcy();
    public void setFeeAmount(BigDecimal feeAmount);
    public BigDecimal getFeeAmount();
    public void setRegisterDate(String registerDate);
    public String getRegisterDate();
    public void setRegisterTime(String registerTime);
    public String getRegisterTime();
    public void setRegisterBy(String registerBy);
    public String getRegisterBy();
    public void setRemark(String remark);
    public String getRemark();
    public void setLastUpdateDate(String lastUpdateDate);
    public String getLastUpdateDate();
    public void setLastUpdateTime(String lastUpdateTime);
    public String getLastUpdateTime();
    public void setLastUpdateUserId(String lastUpdateUserId);
    public String getLastUpdateUserId();
    public void setMisSendDate(String misSendDate);
    public String getMisSendDate();
    public void setCifName(String cifName);
    public String getCifName();
    public void setIssueDate(String issueDate);
    public String getIssueDate();
}